Fixed build by reverting to 2.10.0
Running `mvn test` was failing with:
```
*** RUN ABORTED ***
  java.lang.IncompatibleClassChangeError: class com.twitter.finatra.Examp
leSpec has interface com.twitter.finatra.test.SpecHelper as super class
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
```

Turns out the answer was in this warning just before the error:
```
[INFO] --- scala-maven-plugin:3.1.0:compile (default) @ finatra ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.2
[WARNING]  com.twitter:finatra:1.4.2-SNAPSHOT requires scala version: 2.10.2
[WARNING]  com.twitter:twitter-server_2.10:1.1.0 requires scala version: 2.10.0
[WARNING] Multiple versions of scala libraries detected!
```

So this reverted to Scala 2.10.0 until twitter-server and others upgrade.